### ISSUE TITLE
Error: Member not found: 'DefaultTabController.maybeOf'.

### ISSUE THREAD

**Issue by CohenTT** [hacktons/convex_bottom_bar#191] opened 2023-02-13 14:20 UTC
v3.2.0
iPhone 14 Pro， simulator，iOS  16.1

I get an error when I start running：
../../flutter_mac/flutter/.pub-cache/hosted/pub.flutter-io.cn/convex_bottom_bar-3.2.0/lib/src/bar.dart:478:54: Error: Member not found: 'DefaultTabController.maybeOf'.
    return widget.controller ?? DefaultTabController.maybeOf(context);
                                                     ^^^^^^^

**Comment by avenwu** [comment] 2023-02-14 01:56
Upgrade to flutter v3.7.0+. Or downgrade the package version to v3.0.1+1
Checkout the [README.md](https://github.com/hacktons/convex_bottom_bar#user-content-how-to-use) for more detail.

**Comment by avenwu** [comment] 2023-02-15 01:23
Duplicate of #188

**Closed as completed by avenwu** 2023-02-15 01:23 UTC
Labels: duplicate
