### ISSUE TITLE
Round portion not changing on manual back button

### ISSUE THREAD

**Issue by Anishs123** [hacktons/convex_bottom_bar#110] opened 2020-10-03 07:02 UTC
convex_bottom_bar not changing the inside round portion on pressing manual back button. My code is 

bottomNavigationBar: ConvexAppBar(
       backgroundColor: Colors.blue,
       items: [
         TabItem(icon: Icons.home, title: 'Home'),
         TabItem(icon: Icons.person, title: 'Profile'),
         TabItem(icon: Icons.import_contacts, title: 'Booking'),
         TabItem(icon: Icons.search, title: 'Search'),
         TabItem(icon: Icons.assignment_turned_in, title: 'History'),
       ],
       initialActiveIndex: selectedPos, 
       onTap: (int i) {
         if (i == 1) {
           Navigator.push(context, MaterialPageRoute(builder: (context) {
             return ProfilePage();
           }));
         }
         if (i == 2) {
           Navigator.push(context, MaterialPageRoute(builder: (context) {
             return BookingHistory();
           }));

**Comment by avenwu** [comment] 2020-10-03 08:43
please post issue according to issue template

**Comment by Anishs123** [comment] 2020-10-03 11:17
While clicking the phone manual back button  In my convex bottom bar the top curve is moving to current page button. But the active color round part is not moving properly. It is staying back still in the old page position.

**Comment by avenwu** [comment] 2020-10-09 05:44
I didn't see how you're updating  `selectedPos`. The active index is self-managed, there's no need to track and set with `initialActiveIndex`, it's only used for initial.

**Comment by avenwu** [comment] 2020-10-12 01:22
Duplicate of #112

**Closed by avenwu** 2020-10-12 01:22 UTC
Labels: detail required
