### ISSUE TITLE
Error: Member not found: 'DefaultTabController.maybeOf'. Issue

### ISSUE THREAD

**Issue by Phero49** [hacktons/convex_bottom_bar#193] opened 2023-02-15 05:47 UTC
`Compile failed

../.pub-cache/hosted/pub.dartlang.org/convex_bottom_bar-3.2.0/lib/src/bar.dart:478:54: Error: Member not found: 'DefaultTabController.maybeOf'.

    return widget.controller ?? DefaultTabController.maybeOf(context);

                                                     ^^^^^^^`

**Comment by Phero49** [comment] 2023-02-15 05:49
Am getting this issue when ever i run the code with the package

**Comment by avenwu** [comment] 2023-02-15 06:21
Duplicate of #188

**Closed as completed by avenwu** 2023-02-15 06:21 UTC

**Comment by hp0632** [comment] 2023-03-20 04:16
this #188 can't be fixed this problem , flutter version 3.3.9, the bottom_bar is 3.2.0 . I try it but can't work .

**Comment by avenwu** [comment] 2023-05-24 01:37
There can be some misleading. #188 means you need to upgrade to flutter v3.7.0+ or downgrade the package version to v3.0.1+1

> You may also update to [3.2.0](https://pub.dev/packages/convex_bottom_bar/versions/3.2.0) which fix the compiling error when using flutter 3.7

I did not found the change list of when "DefaultTabController.maybeOf" was first introduced, but flutter 3.7 has this api, maybe 3.6 too.
