### ISSUE TITLE
Programmaticlly Set Active Tab

### ISSUE THREAD

**Issue by roberteverman** [hacktons/convex_bottom_bar#29] opened 2020-02-14 14:44 UTC
Would it be possible to add a method to set the active tab programmatically (without tapping)?

**Comment by avenwu** [comment] 2020-02-15 04:39
@roberteverman Yes you can.
Try with `initialActiveIndex:2`
Duplicate of #26

**Comment by avenwu** [comment] 2020-02-15 05:18
The issue is closed, fell free to fire another one if you have any other question

**Comment by roberteverman** [comment] 2020-02-15 16:35
Thank you for such a quick response! But sorry, I think I may not have explained what I'm trying to do correctly. I have a separate Carousel Slider widget that I'd like to use to control the Convex Bottom Bar. That is, when I swipe left on the Carousel Slider, I'd like it's onPageChange function to update the Convex Bottom Bar such that animates to the tab to the left. The initialActiveIndex seems to allow me set the active tab when the widget is first created but it doesn't let me animate and update the active tab during run time. Do you have any suggestions?

**Comment by avenwu** [comment] 2020-02-16 14:22
So in your situation something like controller would help. However there is no such thing currently, and it wouldn't be easy to hack from outside the widget. Will work on it, keep an eye on this issue.

**Comment by AlaaEldeenYsr** [comment] 2020-02-16 23:29
i made it just add this method and change the state class name so the user can access it through GlobalKey<ConvexBottomBarState>
![image](https://user-images.githubusercontent.com/52201392/74614944-ef149f00-5124-11ea-8c75-feff1efabcdd.png)

**Comment by AlaaEldeenYsr** [comment] 2020-02-16 23:32
then you can use it as you want
![image](https://user-images.githubusercontent.com/52201392/74614994-4fa3dc00-5125-11ea-8d6b-0b39837d7b0a.png)

**Comment by avenwu** [comment] 2020-02-17 11:03
@AlaaEldeenYsr  Sure. You make any changes to satisfy you app；

**Comment by avenwu** [comment] 2020-02-17 11:10
@roberteverman We've release a new version `2.1.0-beta` which supports `TabController`;
Now you can change the index of AppBar similar as the `TabBar` way:
```dart
DefaultTabController(
  length: 5,
  child: Scaffold(
    appBar: AppBar(title: const Text('Custom ConvexAppBar')),
    body: TabBarView(
      children: ['A','B','C','D','E']
          .map((i) => Center(child: Text('$i')))
          .toList(growable: false),
    ),
    bottomNavigationBar: ConvexAppBar(/* some config*/),
  ),
);
```
Or if you are use `PageView` or `TabController` directly, just set the `controller`:
```dart
 Scaffold(
  appBar: AppBar(title: const Text('Custom ConvexAppBar')),
  body: TabBarView(
    controller: _tabController,
    children: ['A','B','C','D','E']
        .map((i) => Center(child: Text('$i')))
        .toList(growable: false),
  ),
  bottomNavigationBar: ConvexAppBar(tabController: _tabController/* some config*/),
);
```
For more detail, please refer to 
https://github.com/hacktons/convex_bottom_bar/blob/master/doc/issue-change-active-tab-index.md

**Comment by roberteverman** [comment] 2020-02-17 12:40
@avenwu This is awesome. Thank you so much. Not all heroes wear capes!

**Comment by avenwu** [comment] 2020-02-17 13:07
@roberteverman Happy coding！ 😄
If you like this project, please support it by star and click like👍 on [pub.dev](https://pub.dev/packages/convex_bottom_bar)

**Comment by AlaaEldeenYsr** [comment] 2020-02-17 13:09
@avenwu But it's not compatible with rtl

**Comment by AlaaEldeenYsr** [comment] 2020-02-17 13:16
@avenwu  But it's not compatible with rtl.
If you can just make the state class name without underscore so we can access it in a raw way it will be better

**Comment by avenwu** [comment] 2020-02-17 13:52
@AlaaEldeenYsr Well that's true, the package does not have internal RTL support;

The `_State` was not exposed to developer just because it would benefit to internal changes; However it's not a big deal to expose it, so you can access the raw way;

**Comment by Hossein-Kia** [comment] 2020-02-18 12:37
Thank you for This awesome library
i used the viewpager and it didn't worked
ConvexAppBar wont accept PageController. please help me.

what is difference between ViewPager and TabBarView?

**Comment by avenwu** [comment] 2020-02-18 14:43
@Hossein-Kia  The support for controller is still in beta version;  Recently we've add the TabController to  work with ConvexAppBar, but not PageController;

The TabBarView use PageView internal which support TabController; If you need to access index manually with PageView, you may need the `ConvexAppBarState`, just as @AlaaEldeenYsr  suggested, **the raw way**.

## How to
Update to `2.1.0-beta+1`;
```dart
// define field instance
GlobalKey<ConvexAppBarState> _appBarKey = GlobalKey<ConvexAppBarState>();
// construct with key
ConvexAppBar(key: _appBarKey, /* ... */);
// change tab index in onPageChanged
_appBarKey.currentState.animateTo(2/* index*/);
```

**Closed** 2020-02-19 08:50 UTC
Labels: enhancement
