### ISSUE TITLE
WEB can't be built

### ISSUE THREAD

**Issue by NaingMyoThawNMYT** [hacktons/convex_bottom_bar#194] opened 2023-02-22 05:55 UTC
💪 Building with sound null safety 💪

Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.
../../../../Applications/flutter/.pub-cache/hosted/pub.dartlang.org/convex_bottom_bar-3.2.0/lib/src/bar.dart:478:54:
Error: Member not found: 'DefaultTabController.maybeOf'.
    return widget.controller ?? DefaultTabController.maybeOf(context);
                                                     ^^^^^^^
Error: Compilation failed.

Compiling lib/main.dart for the Web...                              6.8s
Exception: Failed to compile application for the Web.

**Comment by avenwu** [comment] 2023-02-23 01:12
Duplicate of #188

**Comment by lsosa81** [comment] 2023-03-10 06:53
../../../DevTools/flutter/.pub-cache/hosted/pub.dartlang.org/convex_bottom_bar-3.2.0/lib/src/bar.dart:478:54: Error: Member not found: 'DefaultTabController.maybeOf'.
    return widget.controller ?? DefaultTabController.maybeOf(context);
                                                     ^^^^^^^

**Closed as completed** 2023-05-04 02:28 UTC
Labels: duplicate
